import { IUser } from "@/interfaces/IUser";

export const users: IUser[] = [
    {
      id: 1,
      name: "Tomas Laprovitta",
      email: "tomas@gmail.com",
      password: "123456",
      rol: "Usuario",
      phone: "9875123456",
      address: "Calle Falsa",
      city: "Ciudad Falsa",
      country: "Argentina",
      isActive: true,
      entry_date: new Date(),
    },
    {
      id: 2,
      name: "Danel Torchiari",
      email: "juan@gmail.com",
      password: "123456",
      rol: "Entrenador",
      phone: "123456789",
      address: "Calle 123",
      city: "Ciudad Falsa",
      country: "Argentina",
      isActive: false,
      entry_date: new Date(),
    },
    {
      id: 3,
      name: "Alexander Van Strahlen",
      email: "pedro@gmail.com",
      password: "123456",
      rol: "Usuario",
      phone: "123456789",
      address: "Calle 123",
      city: "Ciudad Falsa",
      country: "Argentina",
      isActive: true,
      entry_date: new Date(),
    },
    {
      id: 4,
      name: "Gustavo Galdeano",
      email: "adriel@gmail.com",
      password: "123456",
      rol: "Entrenador",
      phone: "123456789",
      address: "Calle 123",
      city: "Ciudad Falsa",
      country: "Argentina",
      isActive: true,
      entry_date: new Date(),
    },
    {
        id: 5,
        name: "Adriel Perez",
        email: "adriel@gmail.com",
        password: "123456",
        rol: "Entrenador",
        phone: "123456789",
        address: "Calle 123",
        city: "Ciudad Falsa",
        country: "Argentina",
        isActive: true,
        entry_date: new Date(),
      },
      {
        id: 6,
        name: "Enrique Castillo",
        email: "juan@gmail.com",
        password: "123456",
        rol: "Entrenador",
        phone: "123456789",
        address: "Calle 123",
        city: "Ciudad Falsa",
        country: "Argentina",
        isActive: false,
        entry_date: new Date(),
      },
      {
        id: 7,
        name: "Omar Caiguan",
        email: "juan@gmail.com",
        password: "123456",
        rol: "Entrenador",
        phone: "123456789",
        address: "Calle 123",
        city: "Ciudad Falsa",
        country: "Argentina",
        isActive: false,
        entry_date: new Date(),
      },
]