import { IUser } from "@/interfaces/IUser";

export const users: IUser[] = [
  {
    id: 1,
    name: "Tomas Martinez",
    email: "tomas@gmail.com",
    password: "123456",
    rol: "Usuario",
    phone: "+54-011345251",
    address: "Calle Falsa",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-01-01"),
  },
  {
    id: 2,
    name: "Ana López",
    email: "ana.lopez@gmail.com",
    password: "654321",
    rol: "Usuario",
    phone: "+54-0111234567",
    address: "Av. Siempre Viva",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-01-10"),
  },
  {
    id: 3,
    name: "Carlos Pérez",
    email: "carlos.perez@gmail.com",
    password: "password123",
    rol: "Usuario",
    phone: "+54-0119876543",
    address: "Calle Central",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-01-15"),
  },
  {
    id: 4,
    name: "Lucía Fernández",
    email: "lucia.fernandez@gmail.com",
    password: "mypassword",
    rol: "Usuario",
    phone: "+54-0117654321",
    address: "Paseo del Prado",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-01-20"),
  },
  {
    id: 5,
    name: "Pedro Martínez",
    email: "pedro.martinez@gmail.com",
    password: "admin123",
    rol: "Usuario",
    phone: "+54-0114567890",
    address: "Calle Peatonal",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-02-01"),
  },
  {
    id: 6,
    name: "María Gómez",
    email: "maria.gomez@gmail.com",
    password: "securepass",
    rol: "Usuario",
    phone: "+54-0116543210",
    address: "Calle Nueva",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-02-10"),
  },
  {
    id: 7,
    name: "Jorge Ruiz",
    email: "jorge.ruiz@gmail.com",
    password: "ruiz123",
    rol: "Usuario",
    phone: "+54-0113214567",
    address: "Calle Azul",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-02-15"),
  },
  {
    id: 8,
    name: "Sofía Sánchez",
    email: "sofia.sanchez@gmail.com",
    password: "password2023",
    rol: "Usuario",
    phone: "+54-0115678901",
    address: "Calle Roja",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-02-20"),
  },
  {
    id: 9,
    name: "Ricardo Castro",
    email: "ricardo.castro@gmail.com",
    password: "castro2023",
    rol: "Usuario",
    phone: "+54-0114321567",
    address: "Calle Amarilla",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-03-01"),
  },
  {
    id: 10,
    name: "Laura García",
    email: "laura.garcia@gmail.com",
    password: "laura123",
    rol: "Usuario",
    phone: "+54-0117890123",
    address: "Calle Verde",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-03-05"),
  },
  {
    id: 11,
    name: "Luis Torres",
    email: "luis.torres@gmail.com",
    password: "torres123",
    rol: "Usuario",
    phone: "+54-0118901234",
    address: "Calle Blanca",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-03-10"),
  },
  {
    id: 12,
    name: "Gabriela Romero",
    email: "gabriela.romero@gmail.com",
    password: "gabriela2023",
    rol: "Usuario",
    phone: "+54-0119012345",
    address: "Calle Negra",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-03-15"),
  },
  {
    id: 13,
    name: "Diego Navarro",
    email: "diego.navarro@gmail.com",
    password: "navarro123",
    rol: "Usuario",
    phone: "+54-0116789012",
    address: "Calle Morada",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-03-20"),
  },
  {
    id: 14,
    name: "Valentina Ruiz",
    email: "valentina.ruiz@gmail.com",
    password: "valentina123",
    rol: "Usuario",
    phone: "+54-0117896543",
    address: "Calle Naranja",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-03-25"),
  },
  {
    id: 15,
    name: "Sebastián Vega",
    email: "sebastian.vega@gmail.com",
    password: "vega123",
    rol: "Usuario",
    phone: "+54-0110987654",
    address: "Calle Gris",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-04-01"),
  },
  {
    id: 16,
    name: "Camila Herrera",
    email: "camila.herrera@gmail.com",
    password: "herrera123",
    rol: "Usuario",
    phone: "+54-0119876500",
    address: "Calle Violeta",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-04-05"),
  },
  {
    id: 17,
    name: "Manuel Morales",
    email: "manuel.morales@gmail.com",
    password: "manuel123",
    rol: "Usuario",
    phone: "+54-0118765432",
    address: "Calle Dorada",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-04-10"),
  },
  {
    id: 18,
    name: "Andrea Castro",
    email: "andrea.castro@gmail.com",
    password: "castro2023",
    rol: "Usuario",
    phone: "+54-0117654321",
    address: "Calle Plateada",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-04-15"),
  },
  {
    id: 19,
    name: "Pablo Medina",
    email: "pablo.medina@gmail.com",
    password: "medina123",
    rol: "Usuario",
    phone: "+54-0116543210",
    address: "Calle Brillante",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-04-20"),
  },
  {
    id: 20,
    name: "Elena Ortiz",
    email: "elena.ortiz@gmail.com",
    password: "ortiz123",
    rol: "Usuario",
    phone: "+54-0115432109",
    address: "Calle Estrella",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-04-25"),
  },
  {
    id: 21,
    name: "Rodrigo Flores",
    email: "rodrigo.flores@gmail.com",
    password: "flores123",
    rol: "Usuario",
    phone: "+54-0114321098",
    address: "Calle Cielo",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-05-01"),
  },
  {
    id: 22,
    name: "Natalia Vázquez",
    email: "natalia.vazquez@gmail.com",
    password: "vazquez123",
    rol: "Usuario",
    phone: "+54-0113210987",
    address: "Calle Luna",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-05-05"),
  },
  {
    id: 23,
    name: "Santiago Bustos",
    email: "santiago.bustos@gmail.com",
    password: "bustos123",
    rol: "Usuario",
    phone: "+54-0112109876",
    address: "Calle Sol",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-05-10"),
  },
  {
    id: 24,
    name: "Julieta Campos",
    email: "julieta.campos@gmail.com",
    password: "campos123",
    rol: "Usuario",
    phone: "+54-0111098765",
    address: "Calle Mar",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: false,
    entry_date: new Date("2023-05-15"),
  },
  {
    id: 25,
    name: "Emiliano Ríos",
    email: "emiliano.rios@gmail.com",
    password: "rios123",
    rol: "Usuario",
    phone: "+54-0110987654",
    address: "Calle Río",
    city: "Ciudad Falsa",
    country: "Argentina",
    isActive: true,
    entry_date: new Date("2023-05-20"),
  },
];
